# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='call_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='first name and last name')),
                ('email', models.CharField(max_length=60, verbose_name='email who that sent message')),
                ('phonenumber', models.IntegerField(verbose_name='phone number who that sent message')),
                ('content', models.TextField(verbose_name="Sender's message")),
            ],
        ),
    ]
