# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realityapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call_us',
            name='phonenumber',
            field=models.CharField(max_length=12, verbose_name='phone number who that sent message'),
        ),
    ]
